// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Management.PowerShell")>]
[<assembly: AssemblyProductAttribute("FSharp.Management.PowerShell")>]
[<assembly: AssemblyDescriptionAttribute("Various type providers for management of the machine.")>]
[<assembly: AssemblyVersionAttribute("0.4.4")>]
[<assembly: AssemblyFileVersionAttribute("0.4.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Management.PowerShell"
    let [<Literal>] AssemblyProduct = "FSharp.Management.PowerShell"
    let [<Literal>] AssemblyDescription = "Various type providers for management of the machine."
    let [<Literal>] AssemblyVersion = "0.4.4"
    let [<Literal>] AssemblyFileVersion = "0.4.4"
